//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPersonDto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPersonDto()
        {
            this.PersonalTargets = new HashSet<CPersonalTargetDto>();
            this.Reminders = new HashSet<CReminderDto>();
            this.SpendingHistories = new HashSet<CSpendingHistoryDto>();
            this.SubCategories = new HashSet<CSubCategoryDto>();
        }
    
        public int PersonID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public Nullable<int> Budget { get; set; }
    
        public virtual CFamilyDto Family { get; set; }
        public virtual CLoginDataDto LoginData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPersonalTargetDto> PersonalTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CReminderDto> Reminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSpendingHistoryDto> SpendingHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSubCategoryDto> SubCategories { get; set; }
    }
}
