//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPersonalTargetDto
    {
        public int PersonID { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime Month { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public bool IsGeneral { get; set; }
        public bool IsComplited { get; set; }
    
        public virtual CCategoryDto Category { get; set; }
        public virtual CPersonDto Person { get; set; }
    }
}
