//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSpendingHistoryDto
    {
        public int PersonID { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime Month { get; set; }
        public decimal Spended { get; set; }
    
        public virtual CCategoryDto Category { get; set; }
        public virtual CPersonDto Person { get; set; }
    }
}
