//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpendingHelperDBEntities : DbContext
    {
        public SpendingHelperDBEntities()
            : base("name=SpendingHelperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CCategoryDto> CCategoriesDto { get; set; }
        public virtual DbSet<CFamilyDto> CFamiliesDto { get; set; }
        public virtual DbSet<CFamilyTargetDto> CFamilyTargetsDto { get; set; }
        public virtual DbSet<CLoginDataDto> CLoginDatasDto { get; set; }
        public virtual DbSet<CPaymentDto> CPaymentsDto { get; set; }
        public virtual DbSet<CPersonDto> CPeopleDto { get; set; }
        public virtual DbSet<CPersonalTargetDto> CPersonalTargetsDto { get; set; }
        public virtual DbSet<CReminderDto> CRemindersDto { get; set; }
        public virtual DbSet<CSpendingHistoryDto> CSpendingHistoriesDto { get; set; }
        public virtual DbSet<CSubCategoryDto> CSubCategoriesDto { get; set; }
    }
}
